/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-03-18 11:46:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.auth;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dangky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1766556691885L));
    _jspx_dependants.put("jar:file:/C:/Users/ASUS/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>Đăng ký – Quản Lý Sinh Viên</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body { background: linear-gradient(135deg,#1e4d8c 0%,#2c6fad 60%,#4a9fd4 100%); min-height:100vh; display:flex; align-items:center; justify-content:center; padding:24px; }\n");
      out.write("        .auth-box { background:#fff; border-radius:12px; box-shadow:0 8px 32px rgba(0,0,0,.25); width:100%; max-width:480px; overflow:hidden; }\n");
      out.write("        .auth-header { background:linear-gradient(135deg,#1e4d8c,#2c6fad); color:#fff; text-align:center; padding:28px 24px 20px; }\n");
      out.write("        .auth-header .logo { font-size:42px; margin-bottom:6px; }\n");
      out.write("        .auth-header h1 { font-size:18px; font-weight:700; margin:0; }\n");
      out.write("        .auth-header p  { font-size:13px; opacity:.85; margin:4px 0 0; }\n");
      out.write("        .auth-body { padding:24px 32px 28px; }\n");
      out.write("        .form-group { margin-bottom:16px; }\n");
      out.write("        .form-group label { font-weight:600; font-size:13px; color:#444; margin-bottom:5px; display:block; }\n");
      out.write("        .input-icon { position:relative; }\n");
      out.write("        .input-icon span.icon { position:absolute; left:11px; top:50%; transform:translateY(-50%); font-size:15px; pointer-events:none; }\n");
      out.write("        .input-icon input { padding-left:36px; width:100%; padding-top:9px; padding-bottom:9px; border:1.5px solid #d0dce8; border-radius:6px; font-size:14px; transition:border-color .2s; }\n");
      out.write("        .input-icon input:focus { border-color:#2c6fad; outline:none; box-shadow:0 0 0 3px rgba(44,111,173,.12); }\n");
      out.write("        .input-icon input.error { border-color:#dc3545; }\n");
      out.write("        .strength-bar { height:4px; border-radius:2px; margin-top:5px; background:#eee; overflow:hidden; }\n");
      out.write("        .strength-fill { height:100%; width:0; border-radius:2px; transition:width .3s, background .3s; }\n");
      out.write("        .strength-hint { font-size:11px; color:#888; margin-top:3px; }\n");
      out.write("        .btn-register { width:100%; padding:12px; background:linear-gradient(135deg,#1e4d8c,#2c6fad); color:white; border:none; border-radius:6px; font-size:15px; font-weight:600; cursor:pointer; transition:opacity .2s, transform .1s; }\n");
      out.write("        .btn-register:hover { opacity:.9; transform:translateY(-1px); }\n");
      out.write("        .auth-footer { text-align:center; margin-top:18px; font-size:13px; color:#666; }\n");
      out.write("        .auth-footer a { color:#2c6fad; font-weight:600; text-decoration:none; }\n");
      out.write("        .show-pw { position:absolute; right:10px; top:50%; transform:translateY(-50%); cursor:pointer; font-size:15px; background:none; border:none; padding:0; color:#888; }\n");
      out.write("        .req-list { font-size:12px; color:#888; margin:4px 0 0 0; padding-left:16px; }\n");
      out.write("        .req-list li.ok  { color:#28a745; }\n");
      out.write("        .req-list li.bad { color:#dc3545; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"auth-box\">\n");
      out.write("    <div class=\"auth-header\">\n");
      out.write("        <div class=\"logo\">📝</div>\n");
      out.write("        <h1>TẠO TÀI KHOẢN MỚI</h1>\n");
      out.write("        <p>Hệ Thống Quản Lý Sinh Viên</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"auth-body\">\n");
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dangky\" onsubmit=\"return validateForm()\">\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>Tên đăng nhập <span style=\"color:red\">*</span></label>\n");
      out.write("                <div class=\"input-icon\">\n");
      out.write("                    <span class=\"icon\">👤</span>\n");
      out.write("                    <input type=\"text\" name=\"tenDangNhap\" id=\"tenDangNhap\" required\n");
      out.write("                           value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tenDangNhap}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"4–50 ký tự, chữ/số/_\"\n");
      out.write("                           maxlength=\"50\" oninput=\"checkUsername(this)\">\n");
      out.write("                </div>\n");
      out.write("                <div id=\"usernameMsg\" style=\"font-size:12px;margin-top:3px\"></div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>Họ và tên <span style=\"color:red\">*</span></label>\n");
      out.write("                <div class=\"input-icon\">\n");
      out.write("                    <span class=\"icon\">🪪</span>\n");
      out.write("                    <input type=\"text\" name=\"hoTen\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hoTen}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("                           placeholder=\"VD: Nguyễn Văn An\" maxlength=\"100\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>Email <span style=\"color:red\">*</span></label>\n");
      out.write("                <div class=\"input-icon\">\n");
      out.write("                    <span class=\"icon\">✉️</span>\n");
      out.write("                    <input type=\"email\" name=\"email\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("                           placeholder=\"VD: example@email.com\" maxlength=\"100\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>Mật khẩu <span style=\"color:red\">*</span></label>\n");
      out.write("                <div class=\"input-icon\" style=\"position:relative\">\n");
      out.write("                    <span class=\"icon\">🔒</span>\n");
      out.write("                    <input type=\"password\" name=\"matKhau\" id=\"matKhau\" required\n");
      out.write("                           placeholder=\"Ít nhất 8 ký tự\" oninput=\"checkStrength(this.value)\">\n");
      out.write("                    <button type=\"button\" class=\"show-pw\" onclick=\"togglePw('matKhau','eye1')\">\n");
      out.write("                        <span id=\"eye1\">👁️</span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"strength-bar\"><div class=\"strength-fill\" id=\"strengthFill\"></div></div>\n");
      out.write("                <ul class=\"req-list\" id=\"reqList\">\n");
      out.write("                    <li id=\"req-len\">Ít nhất 8 ký tự</li>\n");
      out.write("                    <li id=\"req-upper\">Có chữ hoa (A–Z)</li>\n");
      out.write("                    <li id=\"req-lower\">Có chữ thường (a–z)</li>\n");
      out.write("                    <li id=\"req-digit\">Có chữ số (0–9)</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>Xác nhận mật khẩu <span style=\"color:red\">*</span></label>\n");
      out.write("                <div class=\"input-icon\" style=\"position:relative\">\n");
      out.write("                    <span class=\"icon\">🔐</span>\n");
      out.write("                    <input type=\"password\" name=\"xacNhanMK\" id=\"xacNhanMK\" required\n");
      out.write("                           placeholder=\"Nhập lại mật khẩu\" oninput=\"checkMatch()\">\n");
      out.write("                    <button type=\"button\" class=\"show-pw\" onclick=\"togglePw('xacNhanMK','eye2')\">\n");
      out.write("                        <span id=\"eye2\">👁️</span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"matchMsg\" style=\"font-size:12px;margin-top:3px\"></div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"btn-register\">✅ ĐĂNG KÝ</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <div class=\"auth-footer\">\n");
      out.write("            Đã có tài khoản? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Đăng nhập</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function togglePw(id, iconId) {\n");
      out.write("    const f = document.getElementById(id);\n");
      out.write("    const e = document.getElementById(iconId);\n");
      out.write("    f.type = f.type === 'password' ? 'text' : 'password';\n");
      out.write("    e.textContent = f.type === 'password' ? '👁️' : '🙈';\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkUsername(inp) {\n");
      out.write("    const msg = document.getElementById('usernameMsg');\n");
      out.write("    const v = inp.value.trim();\n");
      out.write("    if (v.length < 4)                      { msg.style.color='#dc3545'; msg.textContent='⚠ Tối thiểu 4 ký tự'; }\n");
      out.write("    else if (!/^[a-zA-Z0-9_]+$/.test(v))  { msg.style.color='#dc3545'; msg.textContent='⚠ Chỉ được dùng chữ, số, _'; }\n");
      out.write("    else                                    { msg.style.color='#28a745'; msg.textContent='✔ Hợp lệ'; }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkStrength(pw) {\n");
      out.write("    const len   = pw.length >= 8;\n");
      out.write("    const upper = /[A-Z]/.test(pw);\n");
      out.write("    const lower = /[a-z]/.test(pw);\n");
      out.write("    const digit = /[0-9]/.test(pw);\n");
      out.write("    const score = [len, upper, lower, digit].filter(Boolean).length;\n");
      out.write("\n");
      out.write("    const fill  = document.getElementById('strengthFill');\n");
      out.write("    const colors = ['#dc3545','#fd7e14','#ffc107','#28a745'];\n");
      out.write("    fill.style.width   = (score * 25) + '%';\n");
      out.write("    fill.style.background = colors[score - 1] || '#eee';\n");
      out.write("\n");
      out.write("    const toggle = (id, ok) => {\n");
      out.write("        const el = document.getElementById(id);\n");
      out.write("        el.className = ok ? 'ok' : 'bad';\n");
      out.write("    };\n");
      out.write("    toggle('req-len',   len);\n");
      out.write("    toggle('req-upper', upper);\n");
      out.write("    toggle('req-lower', lower);\n");
      out.write("    toggle('req-digit', digit);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkMatch() {\n");
      out.write("    const pw  = document.getElementById('matKhau').value;\n");
      out.write("    const pw2 = document.getElementById('xacNhanMK').value;\n");
      out.write("    const msg = document.getElementById('matchMsg');\n");
      out.write("    if (!pw2) { msg.textContent = ''; return; }\n");
      out.write("    if (pw === pw2) { msg.style.color='#28a745'; msg.textContent='✔ Mật khẩu khớp'; }\n");
      out.write("    else            { msg.style.color='#dc3545'; msg.textContent='✖ Mật khẩu không khớp'; }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function validateForm() {\n");
      out.write("    const pw  = document.getElementById('matKhau').value;\n");
      out.write("    const pw2 = document.getElementById('xacNhanMK').value;\n");
      out.write("    if (pw !== pw2) { alert('Xác nhận mật khẩu không khớp!'); return false; }\n");
      out.write("    const len   = pw.length >= 8;\n");
      out.write("    const upper = /[A-Z]/.test(pw);\n");
      out.write("    const lower = /[a-z]/.test(pw);\n");
      out.write("    const digit = /[0-9]/.test(pw);\n");
      out.write("    if (!len || !upper || !lower || !digit) {\n");
      out.write("        alert('Mật khẩu chưa đủ mạnh. Vui lòng kiểm tra lại yêu cầu!');\n");
      out.write("        return false;\n");
      out.write("    }\n");
      out.write("    return true;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /views/auth/dangky.jsp(47,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("            <div class=\"alert alert-danger\" style=\"margin-bottom:16px\">✖ ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
